apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: subtext

resources:
- namespace.yaml
- api-deployment.yaml
- api-service.yaml
- network-policies.yaml

images:
- digest: sha256:540b26fd3f89f29cf4fbd6ab1c7de932e5f1739c8934116740878304d04175e9
  name: ghcr.io/madfam-org/subtext-api
  newName: ghcr.io/madfam-org/subtext-api
