apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: subtext

resources:
- namespace.yaml
- api-deployment.yaml
- api-service.yaml
- network-policies.yaml

images:
- digest: sha256:d874d633a954694ad5f4d33e3045cb990c93117b93e8ebfa721dcd8610bef57c
  name: ghcr.io/madfam-org/subtext-api
  newName: ghcr.io/madfam-org/subtext-api
