apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: subtext

resources:
- namespace.yaml
- api-deployment.yaml
- api-service.yaml
- network-policies.yaml

images:
- digest: sha256:1b5aba7fccd3986aab546e0b55eab174476e30705bcc002303bca60c9a82bdc3
  name: ghcr.io/madfam-org/subtext-api
  newName: ghcr.io/madfam-org/subtext-api
